# .github/workflows/main.yml
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build . -t mynodeproject --file Dockerfile
      working-directory: ./testrepo

    - name: Run Docker container
      run: docker run mynodeproject
